name: Run tests, deploy tagged releases

on:
  push

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.6", "3.7", "3.8", "3.9", "3.10", "pypy-3.7"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .
          python -m pip install -r test_requirements.txt

      - name: Run unittests
        run: python -m pytest --black --mypy
        if: ${{ !(contains(matrix.python_version, 'pypy') || matrix.python_version == '3.6') }}

      - name: Run unittests (without black/mypy)
        run: python -m pytest
        if: ${{ contains(matrix.python_version, 'pypy') }}

      - name: Verify dependencies
        run: safety check

  deployment:
    name: Deploy a new release to Pypi
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}  # only on tagged commits
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel twine

      - name: Build packages
        run: python setup.py sdist

      - name: Upload packages
        run: python -m twine upload dist/*
        env: 
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

  release:
    name: Create a new release on github
    needs: deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # provided by github actions, no need to configure
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          body: |
            Summary:
              - TODO
